#! /bin/sh
# /etc/init.d/raspcontrol
#

RASPCONTROL=/opt/Raspcontrol
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script raspcontrol"
    cd $RASPCONTROL
    $RASPCONTROL/start.sh >/dev/null &
    ;;
  stop)
    echo "Stopping script raspcontrol"
    echo "Please stop with kill"
    ;;
  *)
    echo "Usage: /etc/init.d/raspcontrol {start|stop}"
    exit 1
    ;;
esac

exit 0

